version: "1"
rules: # Array of rules
    - base: dev # Required. Target branch
      upstream: UjuiUjuMandan:main # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
    - base: dev # Required. Target branch
      upstream: FooIbar:mian # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
    - base: main # Required. Target branch
      upstream: dev # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
