version: "1"
rules: # Array of rules
    - base: dev # Required. Target branch
      upstream: UjuiUjuMandan:1.8.x.x # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
    - base: dev # Required. Target branch
      upstream: FooIbar:1.8.x.x # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
    - base: 1.8.x.x # Required. Target branch
      upstream: dev # Required. Must be in the same fork network.
      mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
      mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: true
